// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdMXzUxJtOsvSjVx0ooltm1-GkDDCRgg',
    appId: '1:1092030296664:web:748217d593a38b7775502d',
    messagingSenderId: '1092030296664',
    projectId: 'fir-testproject-143ff',
    authDomain: 'fir-testproject-143ff.firebaseapp.com',
    storageBucket: 'fir-testproject-143ff.appspot.com',
    measurementId: 'G-XQ1K4HH0VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU3R6cuq0G5JSHuO09Eb50NMGlzEytvjQ',
    appId: '1:1092030296664:android:453ed1f85545cd5775502d',
    messagingSenderId: '1092030296664',
    projectId: 'fir-testproject-143ff',
    storageBucket: 'fir-testproject-143ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATL1TrnYipSaLatgCqknnpm8PiIEmYilg',
    appId: '1:1092030296664:ios:cc3492971253944475502d',
    messagingSenderId: '1092030296664',
    projectId: 'fir-testproject-143ff',
    storageBucket: 'fir-testproject-143ff.appspot.com',
    iosClientId: '1092030296664-kj4sjjaii0acoc76ias8thnfj78a3beb.apps.googleusercontent.com',
    iosBundleId: 'com.example.template',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATL1TrnYipSaLatgCqknnpm8PiIEmYilg',
    appId: '1:1092030296664:ios:cc3492971253944475502d',
    messagingSenderId: '1092030296664',
    projectId: 'fir-testproject-143ff',
    storageBucket: 'fir-testproject-143ff.appspot.com',
    iosClientId: '1092030296664-kj4sjjaii0acoc76ias8thnfj78a3beb.apps.googleusercontent.com',
    iosBundleId: 'com.example.template',
  );
}
